# Generated by Django 3.2.9 on 2022-01-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220105_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tutor', 'Tutor'), ('tutee', 'Tutee')], max_length=10),
        ),
    ]
