# Generated by Django 4.0.2 on 2022-04-11 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220106_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_pw_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_pw_exp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 11, 16, 42, 15, 316083), null=True),
        ),
    ]
