# Generated by Django 4.0.2 on 2022-04-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_reset_pw_code_user_reset_pw_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_pw_exp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
