# Generated by Django 4.0.2 on 2022-04-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_reset_pw_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_pw_code',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
