# Generated by Django 4.0.2 on 2022-04-26 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('reason_for_cancel', models.CharField(blank=True, max_length=150, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_tutee', to=settings.AUTH_USER_MODEL)),
                ('tutor_schedule', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_tutor_schedule', to='api.schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
