# Generated by Django 4.0.2 on 2022-04-26 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tutee', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tutee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_tutee', to='api.tutee'),
        ),
    ]
